# Site settings
title: lytedev
email: daniel@lytedev.io
description: Hi, I'm Daniel! I play with computers for a living.
baseurl: ""
url: "http://lytedev.github.io"
twitter_username: lytedev
github_username: lytedev
permalink: /:title

# Build settings
markdown: kramdown
